### ISSUE TITLE
inject('store') in the provide-inject example is undefined

### ISSUE THREAD

**Issue by Duncank** [lmiller1990/design-patterns-for-vuejs-source-code#1]
I'm trying to make use of the useStore example in the `provide-inject` folder, but the `useStore` import returns undefined, so the `getState` and `addUser` methods are not available either.

I'm not sure how to solve this myself, so hopefully you can help with this!

**Comment by lmiller1990** [comment]
Hi! Sorry, I did not se your issue. You can tag me so I can get a notification. @Duncank.

Can you provide an example of code that isn't working? As far as I can see all the code is okay (tests all passing).

**Comment by Duncank** [comment]
No worries! I've created an example here: [Codesandbox](https://codesandbox.io/s/provideinject-store-example-w0ghu?file=/src/App.vue).

It looks to me like the injected store doesn't work, but the exported store does. The tests only seem to use the exported store, and not the injected one, so that is probably why they aren't catching this.

**Comment by lmiller1990** [comment]
Right, I see the problem. When you use `inject`, you need to have called `provide` with the same key (in this case `'store'`) in some component higher in the hierarchy. I forked and updated your example, [see here](https://codesandbox.io/s/provideinject-store-example-forked-n77w0?file=/src/App.vue).

Basically the change I made was in `main.js`:

```js
import { createApp } from "vue";
import App from "./App.vue";
import { store } from "./store";

const app = createApp(App);
/** This is the important part **/
app.provide("store", store);

app.mount("#app");
```

By doing `provide('store', store)` at the top level, any component that has `inject('store')` called will recursively search upwards until it finds somewhere `provide` was called with a matching key. The [Vue.js 3 docs](https://v3.vuejs.org/guide/composition-api-provide-inject.html#reactivity) have more details.

The reason it works in the [example in the book](https://github.com/lmiller1990/design-patterns-for-vuejs-source-code/blob/0eb882df89cc33d3b0cfdfc67f93c7af803e7099/examples/provide-inject/store.spec.js#L41) is because we do `provide` in the `global` key in Vue Test Utils. Under the hood, this is doing the same thing I described above - it just calls `app.provide` on each of the values passed in `global.provide`. [You can see that here in the source code for Vue Test Utils v2](https://github.com/vuejs/vue-test-utils-next/blob/ee52ecac7f575835f42b503be7d391fe4ac54088/src/mount.ts#L402).

Hopefully that helps, let me know if you have any more questions. Thanks for checking out my content!

**Comment by Duncank** [comment]
Thank you for your response and time you've invested in to this! Your example makes it clear how to use this!
